[[constraint]]
  name = "github.com/gobuffalo/buffalo"
  branch = "development"

# [[constraint]]
#   name = "github.com/gobuffalo/tags"
#   branch = "fix-pagination"

[prune]
  go-tests = true
  unused-packages = true
